export const CONTACT = {
  legalName: "GK GLOBAL GROUP",
  location: "Lomé, Togo — Adidogomé-Soviépé",
  phone: "+228 90 50 36 35", phoneHref: "tel:+22890503635",
  whatsapp: "+228 90 55 98 88", whatsappHref: "https://wa.me/22890559888",
  generalEmail: "info@gkgroup.app", generalEmailHref: "mailto:info@gkgroup.app",
  email: "gk.contactus@gkgroup.app", emailHref: "mailto:gk.contactus@gkgroup.app",
  website: "gkgroup.app",
};

export const SITE_COPY = {
  fr: {
    navigation: { home: "Accueil", about: "À propos", architecture: "Notre architecture", activities: "Nos activités", entities: "Nos entités", nexus: "GK NEXUS", news: "Actualités / Opportunités", contact: "Contact" },
    labels: { discover: "Découvrir", contact: "Nous contacter", language: "Langue" },
    hero: { eyebrow: "Architecture institutionnelle internationale", title: "Global Business Without Borders", description: "GK GROUP relie les opportunités, les expertises et les marchés entre l’Afrique, l’Europe, l’Asie, les Amériques et le reste du monde.", supporting: "Building Trust. Connecting Opportunities." },
    activities: { eyebrow: "Nos domaines d’activité", title: "Des expertises connectées à l’international" },
    entities: { eyebrow: "Notre écosystème", title: "Une architecture claire, des rôles distincts" },
    contact: { eyebrow: "Parlons de vos opportunités", title: "Connectez-vous à GK GROUP" },
    footer: "Architecture institutionnelle globale du groupe.", comingSoon: "Cette page est en préparation dans le cadre de la V2.",
  },
  en: {
    navigation: { home: "Home", about: "About", architecture: "Our architecture", activities: "Our activities", entities: "Our entities", nexus: "GK NEXUS", news: "News / Opportunities", contact: "Contact" },
    labels: { discover: "Discover", contact: "Contact us", language: "Language" },
    hero: { eyebrow: "International institutional architecture", title: "Global Business Without Borders", description: "GK GROUP connects opportunities, expertise and markets across Africa, Europe, Asia, the Americas and the rest of the world.", supporting: "Building Trust. Connecting Opportunities." },
    activities: { eyebrow: "Our areas of activity", title: "Expertise connected internationally" },
    entities: { eyebrow: "Our ecosystem", title: "A clear architecture with distinct roles" },
    contact: { eyebrow: "Let us discuss your opportunities", title: "Connect with GK GROUP" },
    footer: "The group’s global institutional architecture.", comingSoon: "This page is being prepared as part of V2.",
  },
};

export const ACTIVITIES = [
  { id: "technology", fr: "Technology & Digital Solutions", en: "Technology & Digital Solutions" },
  { id: "mobility", fr: "International Mobility", en: "International Mobility" },
  { id: "trade", fr: "International Trade & Import-Export", en: "International Trade & Import-Export" },
  { id: "development", fr: "Business Development", en: "Business Development" },
  { id: "consulting", fr: "Strategic Consulting", en: "Strategic Consulting" },
];

export const ACTIVITY_CONTENT = {
  fr: {
    hero: { eyebrow: "Portefeuille d’activités", title: "Nos activités", description: "GK GROUP développe un portefeuille d’activités complémentaires destiné à connecter les compétences, les marchés et les opportunités entre l’Afrique, l’Europe et les marchés internationaux.", motto: "Global Business Without Borders" },
    domains: { eyebrow: "Cinq domaines d’activité", title: "Des expertises complémentaires, une même ambition", items: [
      { title: "Technology & Digital Solutions", description: "Des solutions technologiques conçues pour accompagner les organisations dans leurs besoins opérationnels et leur évolution digitale.", services: ["Solutions informatiques", "Maintenance et services IT", "Infrastructures et réseaux", "Équipements technologiques", "Solutions digitales", "Accompagnement technologique des organisations"], structures: "Structure principalement liée : GKGT — GK GLOBAL TECHNOLOGY." },
      { title: "International Mobility", description: "Un accompagnement structuré des projets de mobilité internationale, adapté aux parcours académiques, professionnels et institutionnels.", services: ["Mobilité internationale", "Accompagnement des projets de mobilité", "Mobilité professionnelle", "Études à l’étranger", "Missions professionnelles et conférences", "Assistance documentaire et installation internationale"], structures: "Structure principalement liée : GKGM — GK GLOBAL MOBILITY." },
      { title: "International Trade & Import-Export", description: "Des activités dédiées au commerce international, au sourcing et au rapprochement entre marchés européens, africains et internationaux.", services: ["Commerce international et import-export", "Sourcing et recherche de fournisseurs", "Développement des échanges commerciaux", "Mise en relation de marchés", "Partenariats commerciaux", "Échanges Europe–Afrique et internationaux"], structures: "Structures principalement associées : UAB GK-EstTrade, GK Danube Trading DOO et, selon les projets, GK NEXUS." },
      { title: "Business Development", description: "Une approche de développement destinée à identifier, structurer et accompagner des opportunités sur des marchés complémentaires.", services: ["Identification d’opportunités", "Développement de marchés", "Structuration de projets", "Recherche et développement de partenariats", "Accompagnement de l’expansion internationale", "Mise en relation économique et commerciale"], structures: "Mise en œuvre par les structures compétentes du groupe selon les projets et les marchés." },
      { title: "Strategic Consulting", description: "Un accompagnement stratégique pour analyser, structurer et faire progresser les projets internationaux et les partenariats.", services: ["Analyse et structuration de projets", "Conseil en développement international", "Accompagnement stratégique", "Organisation et optimisation des projets", "Appui à la prise de décision", "Développement de partenariats stratégiques"], structures: "Mise en œuvre par les structures compétentes du groupe selon les projets et les marchés." },
    ] },
    complementarity: { eyebrow: "Modèle de complémentarité", title: "Des activités qui se renforcent mutuellement", description: "Ces domaines d’activité ne constituent pas des sociétés ou des filiales. Ils forment un portefeuille coordonné qui peut mobiliser des compétences complémentaires selon les besoins de chaque projet.", result: "Création de solutions et d’opportunités internationales intégrées" },
    structures: { eyebrow: "Structures et activités", title: "Des rôles adaptés à chaque activité", description: "Les activités sont mises en œuvre par différentes structures du groupe selon leur rôle, leur implantation et leurs compétences. Une même structure n’exerce donc pas nécessairement l’ensemble des activités.", links: [{ href: "/entities", label: "Découvrir nos entités" }, { href: "/architecture", label: "Voir notre architecture" }, { href: "/gk-nexus", label: "Découvrir GK NEXUS" }] },
    international: { eyebrow: "Positionnement international", title: "Connecter les marchés avec méthode", description: "Le portefeuille d’activités de GK GROUP vise à favoriser les connexions entre l’Afrique, l’Europe et les marchés internationaux. Cette orientation traduit une vocation internationale, sans assimiler l’horizon stratégique à une présence opérationnelle actuelle." },
    final: { title: "Construisons des opportunités ensemble", entities: "Découvrir nos entités", contact: "Nous contacter" },
  },
  en: {
    hero: { eyebrow: "Activity portfolio", title: "Our Activities", description: "GK GROUP develops a portfolio of complementary activities designed to connect skills, markets and opportunities across Africa, Europe and international markets.", motto: "Global Business Without Borders" },
    domains: { eyebrow: "Five areas of activity", title: "Complementary expertise, one shared ambition", items: [
      { title: "Technology & Digital Solutions", description: "Technology solutions designed to support organisations in their operational needs and digital evolution.", services: ["IT solutions", "IT maintenance and services", "Infrastructure and networks", "Technology equipment", "Digital solutions", "Technology support for organisations"], structures: "Mainly linked structure: GKGT — GK GLOBAL TECHNOLOGY." },
      { title: "International Mobility", description: "Structured support for international mobility projects, adapted to academic, professional and institutional paths.", services: ["International mobility", "Mobility project support", "Professional mobility", "Study abroad", "Professional assignments and conferences", "Documentary assistance and international settlement support"], structures: "Mainly linked structure: GKGM — GK GLOBAL MOBILITY." },
      { title: "International Trade & Import-Export", description: "Activities dedicated to international trade, sourcing and connections between European, African and international markets.", services: ["International trade and import-export", "Sourcing and supplier research", "Trade development", "Market connections", "Commercial partnerships", "Europe–Africa and international exchanges"], structures: "Mainly associated structures: UAB GK-EstTrade, GK Danube Trading DOO and, depending on projects, GK NEXUS." },
      { title: "Business Development", description: "A development approach designed to identify, structure and support opportunities across complementary markets.", services: ["Opportunity identification", "Market development", "Project structuring", "Partnership research and development", "International expansion support", "Economic and commercial connections"], structures: "Implemented by the group’s relevant structures according to projects and markets." },
      { title: "Strategic Consulting", description: "Strategic support to analyse, structure and advance international projects and partnerships.", services: ["Project analysis and structuring", "International development consulting", "Strategic support", "Project organisation and optimisation", "Decision-making support", "Strategic partnership development"], structures: "Implemented by the group’s relevant structures according to projects and markets." },
    ] },
    complementarity: { eyebrow: "Complementarity model", title: "Activities that reinforce one another", description: "These areas of activity are not companies or subsidiaries. They form a coordinated portfolio that can bring together complementary expertise according to the needs of each project.", result: "Creation of integrated international solutions and opportunities" },
    structures: { eyebrow: "Structures and activities", title: "Roles tailored to each activity", description: "Activities are implemented by different group structures according to their role, location and expertise. A single structure does not necessarily carry out every activity.", links: [{ href: "/entities", label: "Discover our entities" }, { href: "/architecture", label: "Explore our architecture" }, { href: "/gk-nexus", label: "Discover GK NEXUS" }] },
    international: { eyebrow: "International positioning", title: "Connecting markets with purpose", description: "GK GROUP’s activity portfolio aims to foster connections between Africa, Europe and international markets. This direction expresses an international vocation, without equating a strategic horizon with a current operational presence." },
    final: { title: "Building Opportunities Together", entities: "Discover our entities", contact: "Contact us" },
  },
};

export const NEXUS_CONTENT = {
  fr: {
    hero: { eyebrow: "Corporate & International Operations", title: "GK NEXUS", description: "GK NEXUS est une société à part entière, conçue comme une plateforme corporate et opérationnelle internationale pour renforcer la coordination, le développement et l’expansion internationale de GK GROUP.", location: "Implantation stratégique prévue : Albanie" },
    vocation: { eyebrow: "Double vocation", title: "Une société, deux dimensions complémentaires", corporate: { title: "Corporate & Group Steering", items: ["Pilotage stratégique", "Coordination du groupe", "Suivi des performances", "Coordination des projets transversaux", "Accompagnement des structures", "Contrôle et suivi des ressources", "Préparation des décisions stratégiques", "Développement international"] }, operations: { title: "Own Business Activities", description: "Dans le cadre de son développement, GK NEXUS peut porter ses propres activités et projets selon les opportunités.", items: ["Technology & Digital Solutions", "International Trade", "International Mobility", "Business Development", "Strategic Projects"] } },
    role: { eyebrow: "Rôle au sein de GK GROUP", title: "Un point de convergence stratégique", description: "GK NEXUS contribue à assurer la cohérence stratégique du groupe, à faciliter la coordination entre les structures et à préparer le développement international progressif.", items: ["Faciliter la coordination entre les structures", "Identifier et structurer de nouvelles opportunités", "Suivre les projets transversaux", "Soutenir la gouvernance", "Contribuer au contrôle des risques et des ressources", "Préparer de nouvelles implantations et partenariats"], cta: "Voir notre architecture" },
    albania: { eyebrow: "Albanie", title: "Une implantation stratégique en Europe", description: "L’Albanie est envisagée comme une future base stratégique et opérationnelle européenne de GK NEXUS. Cette implantation, lorsqu’elle sera développée, pourra contribuer à renforcer les connexions européennes du groupe.", items: ["Coordination du développement international de GK GROUP", "Identification d’opportunités européennes", "Recherche de partenaires", "Développement de relations commerciales", "Recherche de fournisseurs et d’équipements", "Structuration de projets internationaux", "Soutien aux besoins des différentes structures du groupe"] },
    diagram: { eyebrow: "Connexion fonctionnelle", title: "Coordonner les compétences du groupe", note: "Ce schéma illustre une logique fonctionnelle de coordination. Il ne remplace pas et ne modifie pas le diagramme institutionnel officiel présenté dans notre architecture." },
    value: { eyebrow: "Création de valeur", title: "Transformer les opportunités en développement durable", steps: ["GK NEXUS — Pilotage • Coordination • Développement international", "Identification et structuration des opportunités", "Structures du groupe", "Clients • Partenaires • Marchés • Investisseurs", "Création de valeur durable"] },
    interactions: { eyebrow: "Interactions opérationnelles", title: "Des complémentarités au service des projets", items: [{ name: "GKGM", text: "GK NEXUS peut contribuer à identifier et structurer des opportunités internationales liées à la mobilité et aux besoins professionnels." }, { name: "GKGT", text: "GK NEXUS peut contribuer à identifier des fournisseurs, équipements, partenaires et opportunités technologiques." }, { name: "UAB GK-EstTrade", text: "Développement commercial, sourcing, commerce international et connexions Europe–Afrique." }, { name: "GK Danube Trading DOO", text: "Développement de relations commerciales et opportunités en Serbie et dans sa région." }, { name: "GK GLOBAL GROUP SARLU", text: "Coordination institutionnelle, reporting, mise en œuvre des orientations du groupe et développement depuis le Togo." }] },
    vision: { eyebrow: "Vision stratégique 2026–2035", title: "Un levier pour le développement international", description: "GK NEXUS est appelé à soutenir la gouvernance, la coordination, l’expansion progressive, le développement de partenariats, l’innovation, l’excellence opérationnelle et la création de valeur durable." },
    final: { title: "Connecter. Coordonner. Développer.", entities: "Découvrir nos entités", contact: "Nous contacter" },
  },
  en: {
    hero: { eyebrow: "Corporate & International Operations", title: "GK NEXUS", description: "GK NEXUS is a standalone company designed as an international corporate and operational platform to strengthen GK GROUP’s coordination, development and international expansion.", location: "Strategic establishment planned: Albania" },
    vocation: { eyebrow: "Dual purpose", title: "One Company, Two Complementary Dimensions", corporate: { title: "Corporate & Group Steering", items: ["Strategic steering", "Group coordination", "Performance monitoring", "Cross-functional project coordination", "Support for structures", "Resource oversight and monitoring", "Preparation of strategic decisions", "International development"] }, operations: { title: "Own Business Activities", description: "As it develops, GK NEXUS may carry its own activities and projects according to opportunities.", items: ["Technology & Digital Solutions", "International Trade", "International Mobility", "Business Development", "Strategic Projects"] } },
    role: { eyebrow: "Role within GK GROUP", title: "A strategic point of convergence", description: "GK NEXUS contributes to ensuring the group’s strategic coherence, facilitating coordination between structures and preparing progressive international development.", items: ["Facilitate coordination between structures", "Identify and structure new opportunities", "Monitor cross-functional projects", "Support governance", "Contribute to risk and resource oversight", "Prepare new establishments and partnerships"], cta: "View our architecture" },
    albania: { eyebrow: "Albania", title: "A Strategic European Base", description: "Albania is envisaged as a future strategic and operational European base for GK NEXUS. When developed, this establishment may help strengthen the group’s European connections.", items: ["Coordination of GK GROUP’s international development", "Identification of European opportunities", "Partner research", "Development of commercial relationships", "Supplier and equipment research", "Structuring of international projects", "Support for the needs of the group’s various structures"] },
    diagram: { eyebrow: "Functional connection", title: "Coordinating the group’s expertise", note: "This diagram illustrates a functional coordination approach. It does not replace or alter the official institutional diagram presented in our architecture." },
    value: { eyebrow: "Value creation", title: "Turning opportunities into sustainable development", steps: ["GK NEXUS — Steering • Coordination • International development", "Opportunity identification and structuring", "Group structures", "Clients • Partners • Markets • Investors", "Sustainable value creation"] },
    interactions: { eyebrow: "Operational interactions", title: "Complementarity in support of projects", items: [{ name: "GKGM", text: "GK NEXUS may contribute to identifying and structuring international opportunities related to mobility and professional needs." }, { name: "GKGT", text: "GK NEXUS may contribute to identifying suppliers, equipment, partners and technology opportunities." }, { name: "UAB GK-EstTrade", text: "Commercial development, sourcing, international trade and Europe–Africa connections." }, { name: "GK Danube Trading DOO", text: "Development of commercial relationships and opportunities in Serbia and its region." }, { name: "GK GLOBAL GROUP SARLU", text: "Institutional coordination, reporting, implementation of group directions and development from Togo." }] },
    vision: { eyebrow: "Strategic Vision 2026–2035", title: "A Platform for International Development", description: "GK NEXUS is intended to support governance, coordination, progressive expansion, partnership development, innovation, operational excellence and sustainable value creation." },
    final: { title: "Connect. Coordinate. Develop.", entities: "Discover our entities", contact: "Contact us" },
  },
};

export const CONTACT_CONTENT = {
  fr: {
    hero: { title: "Entrons en contact", description: "Une question, un projet ou une opportunité de partenariat ? Échangez avec GK GROUP et identifions ensemble l’interlocuteur adapté à votre demande.", signature: "Building Trust. Connecting Opportunities." },
    details: { eyebrow: "Coordonnées", title: "GK GROUP", generalEmail: "Email général", institutionalEmail: "Contact institutionnel", call: "Appeler", whatsapp: "WhatsApp", whatsappMessage: "Bonjour GK GROUP, je souhaite obtenir des informations concernant vos services." },
    form: { eyebrow: "Votre demande", title: "Parlez-nous de votre projet", intro: "Les champs marqués d’un astérisque sont obligatoires.", fields: { name: "Nom complet", email: "Email", phone: "Téléphone", country: "Pays", organisation: "Société / Organisation", subject: "Objet", area: "Domaine concerné", message: "Message" }, options: ["Technology & Digital Solutions", "Mobilité internationale", "Commerce international & Import-Export", "Business Development", "Strategic Consulting", "Partenariat", "Autre demande"], submit: "Envoyer via WhatsApp", emailAlternative: "Préférer l’email", whatsappInfo: "En choisissant WhatsApp, les informations saisies seront transférées vers WhatsApp afin que vous puissiez envoyer votre demande à GK GROUP.", privacy: "Les informations transmises via ce formulaire sont utilisées uniquement pour traiter votre demande. GK GROUP ne garantit ni visa, ni emploi, ni admission, ni résultat administratif ou commercial." },
    routing: { eyebrow: "Trouver le bon interlocuteur", title: "Une orientation adaptée à votre demande", items: [{ id: "gkgt", name: "GK GLOBAL TECHNOLOGY (GKGT)", text: "Technology & Digital Solutions" }, { id: "gkgm", name: "GK GLOBAL MOBILITY (GKGM)", text: "International Mobility" }, { id: "uab-gk-esttrade", name: "UAB GK-EstTrade", text: "International Trade & Sourcing / échanges Europe–Afrique" }, { id: "gk-danube-trading", name: "GK Danube Trading DOO", text: "International Trade & Development / Serbie" }, { id: "gk-nexus", name: "GK NEXUS", text: "Coordination corporate, business development et projets stratégiques" }, { id: "gk-global-group-sarlu", name: "GK GLOBAL GROUP SARLU", text: "Questions institutionnelles et corporate au Togo" }] },
    partnership: { title: "Construisons des opportunités ensemble", description: "GK GROUP développe des relations avec des entreprises, institutions, fournisseurs, établissements et partenaires internationaux autour de projets technologiques, de mobilité, de commerce, de développement d’affaires et de coopération stratégique.", cta: "Proposer un partenariat" },
  },
  en: {
    hero: { title: "Let’s Connect", description: "Have a question, a project or a partnership opportunity? Connect with GK GROUP and let us identify the right point of contact for your request.", signature: "Building Trust. Connecting Opportunities." },
    details: { eyebrow: "Contact details", title: "GK GROUP", generalEmail: "General Email", institutionalEmail: "Institutional Contact", call: "Call", whatsapp: "WhatsApp", whatsappMessage: "Hello GK GROUP, I would like to get information about your services." },
    form: { eyebrow: "Your inquiry", title: "Tell us about your project", intro: "Fields marked with an asterisk are required.", fields: { name: "Full name", email: "Email", phone: "Phone", country: "Country", organisation: "Company / Organisation", subject: "Subject", area: "Area of interest", message: "Message" }, options: ["Technology & Digital Solutions", "International Mobility", "International Trade & Import-Export", "Business Development", "Strategic Consulting", "Partnership", "Other inquiry"], submit: "Send via WhatsApp", emailAlternative: "Prefer Email", whatsappInfo: "By choosing WhatsApp, the information entered will be transferred to WhatsApp so you can send your inquiry to GK GROUP.", privacy: "Information submitted through this form is used only to process your inquiry. GK GROUP does not guarantee visas, employment, admission, administrative approvals or commercial outcomes." },
    routing: { eyebrow: "Find the Right Contact", title: "Guidance adapted to your inquiry", items: [{ id: "gkgt", name: "GK GLOBAL TECHNOLOGY (GKGT)", text: "Technology & Digital Solutions" }, { id: "gkgm", name: "GK GLOBAL MOBILITY (GKGM)", text: "International Mobility" }, { id: "uab-gk-esttrade", name: "UAB GK-EstTrade", text: "International Trade & Sourcing / Europe–Africa trade" }, { id: "gk-danube-trading", name: "GK Danube Trading DOO", text: "International Trade & Development / Serbia" }, { id: "gk-nexus", name: "GK NEXUS", text: "Corporate coordination, business development and strategic projects" }, { id: "gk-global-group-sarlu", name: "GK GLOBAL GROUP SARLU", text: "Institutional and corporate matters in Togo" }] },
    partnership: { title: "Building Opportunities Together", description: "GK GROUP develops relationships with companies, institutions, suppliers, educational organizations and international partners across technology, mobility, trade, business development and strategic cooperation.", cta: "Partnership Inquiry" },
  },
};

export const NEWS_CATEGORIES = {
  fr: ["Actualités du Groupe", "Partenariats", "Développement international", "Technologie", "Mobilité internationale", "Commerce international", "Business & Stratégie"],
  en: ["Group News", "Partnerships", "International Development", "Technology", "International Mobility", "International Trade", "Business & Strategy"],
};

// Add only validated publications. Each item uses: id, slug, status, date, image,
// structure, category, and a `content` object containing fr/en title, summary and body.
export const NEWS_ITEMS = [];

export const NEWS_CONTENT = {
  fr: {
    hero: { title: "Actualités & Perspectives", description: "Retrouvez les actualités, initiatives, partenariats et développements stratégiques de GK GROUP et de ses structures.", signature: "Building Trust. Connecting Opportunities." },
    state: { eyebrow: "Communication corporate", title: "Nos actualités arrivent bientôt", description: "Cette section présentera les annonces, initiatives, partenariats et développements de GK GROUP et de ses structures." },
    latest: { eyebrow: "Actualités", title: "Dernières publications", readMore: "Lire la suite", structure: "Structure concernée" },
    stayInformed: { title: "Restez informé", description: "Suivez les développements de GK GROUP et découvrez nos initiatives à travers nos différents domaines d’activité.", cta: "Nous contacter" },
  },
  en: {
    hero: { title: "News & Insights", description: "Discover news, initiatives, partnerships and strategic developments from GK GROUP and its structures.", signature: "Building Trust. Connecting Opportunities." },
    state: { eyebrow: "Corporate communication", title: "Our latest news is coming soon", description: "This section will feature announcements, initiatives, partnerships and developments from GK GROUP and its structures." },
    latest: { eyebrow: "News", title: "Latest publications", readMore: "Read more", structure: "Related structure" },
    stayInformed: { title: "Stay Informed", description: "Follow GK GROUP developments and discover our initiatives across our areas of activity.", cta: "Contact Us" },
  },
};

export const ABOUT_CONTENT = {
  fr: {
    hero: { eyebrow: "Architecture institutionnelle internationale", title: "À propos de GK GROUP", description: "GK GROUP est une architecture institutionnelle internationale structurée autour de sociétés, branches et plateformes complémentaires.", motto: "Global Business Without Borders", signature: "Building Trust. Connecting Opportunities." },
    identity: { eyebrow: "Qui sommes-nous ?", title: "Construire un groupe international durable", description: "GK GROUP vise à relier l’Afrique et l’Europe, puis à développer progressivement sa présence internationale au moyen d’activités complémentaires, d’une gouvernance coordonnée et de partenariats durables.", currentLabel: "Présence actuelle et structures", current: ["Togo", "Lituanie", "Serbie"], plannedLabel: "Développement stratégique", planned: "Albanie — implantation stratégique envisagée pour GK NEXUS." },
    vision: { eyebrow: "Vision stratégique 2026–2035", title: "Une organisation conçue pour traverser les générations", description: "Notre ambition est de construire une organisation internationale durable, capable de créer de la valeur avec rigueur, continuité et responsabilité.", pillars: ["Innovation", "Gouvernance", "Développement international", "Création de valeur durable", "Excellence opérationnelle", "Partenariats stratégiques", "Expansion progressive"] },
    founder: { eyebrow: "Mot du fondateur", name: "Edem Yawo Awutey", role: "Fondateur & Directeur Général — GK GROUP", message: ["Notre ambition est de construire un groupe international durable reliant l’Afrique et l’Europe, en créant des passerelles fondées sur la confiance, l’innovation et les opportunités.", "GK GROUP est né de cette vision : connecter les marchés, les compétences et les projets au-delà des frontières, tout en bâtissant des relations durables et créatrices de valeur."], motto: "Global Business Without Borders", emailLabel: "Contact institutionnel", whatsappLabel: "WhatsApp GK GROUP", emailAria: "Contacter GK GROUP par email", whatsappAria: "Contacter GK GROUP via WhatsApp", photoAlt: "Edem Yawo Awutey, Fondateur et Directeur Général de GK GROUP" },
    mission: { eyebrow: "Notre mission", title: "Connecter, structurer et développer", items: ["Connecter les opportunités entre marchés.", "Structurer et développer des activités complémentaires.", "Faciliter les échanges Afrique–Europe.", "Développer des solutions en technologie, mobilité, commerce international, business development et conseil stratégique.", "Construire des partenariats durables."] },
    model: { eyebrow: "Modèle institutionnel", title: "Une coordination claire, des structures autonomes", description: "GK GROUP associe un pilotage coordonné à l’autonomie opérationnelle de ses structures, afin de renforcer leur complémentarité, le suivi des performances et le développement international progressif.", cta: "Découvrir notre architecture", principles: ["Gouvernance et pilotage coordonnés", "Autonomie opérationnelle des structures", "Complémentarité entre les entités", "Contrôle et suivi des performances", "Développement international progressif"] },
    timeline: { eyebrow: "Notre évolution", title: "Une présence construite par étapes", items: [{ title: "Togo", text: "Cadre institutionnel et coordination des activités du groupe." }, { title: "Lituanie et Serbie", text: "Structures internationales dédiées au commerce et au développement international." }, { title: "Albanie", text: "Horizon d’implantation stratégique pour GK NEXUS, à développer progressivement." }] },
    domains: { eyebrow: "Nos domaines", title: "Cinq expertises complémentaires", cta: "Découvrir nos activités" },
    horizon: { eyebrow: "Horizon international", title: "Une vision géographique à long terme", description: "Au-delà de sa présence actuelle, GK GROUP envisage un horizon stratégique de long terme entre l’Afrique, l’Europe, les Amériques et l’Asie-Pacifique. Ces régions expriment une ambition de développement, et non des implantations opérationnelles actuelles." },
  },
  en: {
    hero: { eyebrow: "International institutional architecture", title: "About GK GROUP", description: "GK GROUP is an international institutional architecture structured around complementary companies, branches and platforms.", motto: "Global Business Without Borders", signature: "Building Trust. Connecting Opportunities." },
    identity: { eyebrow: "Who we are", title: "Building a sustainable international group", description: "GK GROUP aims to connect Africa and Europe, then progressively develop its international presence through complementary activities, coordinated governance and lasting partnerships.", currentLabel: "Current presence and structures", current: ["Togo", "Lithuania", "Serbia"], plannedLabel: "Strategic development", planned: "Albania — strategic establishment envisaged for GK NEXUS." },
    vision: { eyebrow: "Strategic Vision 2026–2035", title: "An organisation designed to span generations", description: "Our ambition is to build a sustainable international organisation that creates value with rigour, continuity and responsibility.", pillars: ["Innovation", "Governance", "International development", "Sustainable value creation", "Operational excellence", "Strategic partnerships", "Progressive expansion"] },
    founder: { eyebrow: "Founder’s Message", name: "Edem Yawo Awutey", role: "Founder & Managing Director — GK GROUP", message: ["Our ambition is to build a sustainable international group connecting Africa and Europe, creating bridges founded on trust, innovation and opportunity.", "GK GROUP was born from this vision: connecting markets, skills and projects across borders while building lasting relationships that create value."], motto: "Global Business Without Borders", emailLabel: "Institutional contact", whatsappLabel: "GK GROUP WhatsApp", emailAria: "Contact GK GROUP by email", whatsappAria: "Contact GK GROUP via WhatsApp", photoAlt: "Edem Yawo Awutey, Founder and Managing Director of GK GROUP" },
    mission: { eyebrow: "Our mission", title: "Connect, structure and develop", items: ["Connect opportunities across markets.", "Structure and develop complementary activities.", "Facilitate Africa–Europe exchanges.", "Develop solutions in technology, mobility, international trade, business development and strategic consulting.", "Build lasting partnerships."] },
    model: { eyebrow: "Institutional model", title: "Clear coordination, autonomous structures", description: "GK GROUP combines coordinated steering with the operational autonomy of its structures to strengthen complementarity, performance oversight and progressive international development.", cta: "Discover our architecture", principles: ["Coordinated governance and steering", "Operational autonomy of structures", "Complementarity between entities", "Performance oversight and monitoring", "Progressive international development"] },
    timeline: { eyebrow: "Our evolution", title: "A presence built step by step", items: [{ title: "Togo", text: "Institutional framework and coordination of the group’s activities." }, { title: "Lithuania and Serbia", text: "International structures dedicated to trade and international development." }, { title: "Albania", text: "Strategic establishment horizon for GK NEXUS, to be developed progressively." }] },
    domains: { eyebrow: "Our areas", title: "Five complementary areas of expertise", cta: "Discover our activities" },
    horizon: { eyebrow: "International horizon", title: "A long-term geographic vision", description: "Beyond its current presence, GK GROUP envisages a long-term strategic horizon across Africa, Europe, the Americas and Asia-Pacific. These regions express a development ambition, not current operational establishments." },
  },
};

export const ENTITIES = [
  { id: "gk-global-group-sarlu", name: "GK GLOBAL GROUP SARLU", kind: { fr: "Société de référence juridique au Togo", en: "Reference legal company in Togo" }, location: "Lomé, Togo" },
  { id: "gkgt", name: "GKGT — GK GLOBAL TECHNOLOGY", kind: { fr: "Branche Technology & IT de GK GLOBAL GROUP SARLU", en: "Technology & IT branch of GK GLOBAL GROUP SARLU" }, location: "Lomé, Togo" },
  { id: "gkgm", name: "GKGM — GK GLOBAL MOBILITY", kind: { fr: "Branche International Mobility de GK GLOBAL GROUP SARLU", en: "International Mobility branch of GK GLOBAL GROUP SARLU" }, location: "Lomé, Togo" },
  { id: "gk-nexus", name: "GK NEXUS", kind: { fr: "Société distincte, plateforme Corporate & International Operations", en: "A distinct company and Corporate & International Operations platform" }, location: null },
  { id: "uab-gk-esttrade", name: "UAB GK-EstTrade", kind: { fr: "Société internationale de commerce, sourcing et développement Europe–Afrique", en: "International company for trade, sourcing and Europe–Africa development" }, location: "Lituanie" },
  { id: "gk-danube-trading", name: "GK Danube Trading DOO", kind: { fr: "Société internationale de commerce et développement international", en: "International company for trade and international development" }, location: "Serbie" },
];

export const ENTITY_LOGOS = {
  "gk-global-group-sarlu": { src: "/brand/entities/gk-global-group-sarlu.png", alt: "Logo GK GLOBAL GROUP SARLU" },
  gkgt: { src: "/brand/entities/gk-global-technology.png", alt: "Logo GK GLOBAL TECHNOLOGY (GKGT)" },
  gkgm: { src: "/brand/entities/gk-global-mobility.png", alt: "Logo GK GLOBAL MOBILITY (GKGM)" },
  "gk-nexus": { src: "/brand/entities/gk-nexus.png", alt: "Logo GK NEXUS" },
  "uab-gk-esttrade": { src: "/brand/entities/uab-gk-esttrade.png", alt: "Logo UAB GK-EstTrade" },
  "gk-danube-trading": { src: "/brand/entities/gk-danube-trading.png", alt: "GK Danube Trading DOO" },
};

export const ENTITY_DETAILS = {
  "gk-global-group-sarlu": { domain: { fr: "Cadre institutionnel et coordination", en: "Institutional framework and coordination" }, role: { fr: "Cadre juridique, organisation, administration et coordination des activités au Togo.", en: "Legal framework, organisation, administration and coordination of activities in Togo." }, legal: { fr: { title: "Informations légales", entries: [{ label: "Forme juridique", value: "SARL U" }, { label: "RCCM", value: "TG-LFW-01-2026-B13-02457" }, { label: "NIF", value: "1002141706" }, { label: "Siège social", value: "Lomé, Togo" }] }, en: { title: "Legal Information", entries: [{ label: "Legal form", value: "SARL U" }, { label: "RCCM", value: "TG-LFW-01-2026-B13-02457" }, { label: "Tax ID (NIF)", value: "1002141706" }, { label: "Registered office", value: "Lomé, Togo" }] } } },
  gkgt: { domain: { fr: "Technology & IT", en: "Technology & IT" }, role: { fr: "Branche dédiée aux activités Technology & IT.", en: "Branch dedicated to Technology & IT activities." } },
  gkgm: { domain: { fr: "International Mobility", en: "International Mobility" }, role: { fr: "Branche dédiée aux activités d’International Mobility.", en: "Branch dedicated to International Mobility activities." } },
  "gk-nexus": { domain: { fr: "Corporate & International Operations", en: "Corporate & International Operations" }, role: { fr: "Pilotage, coordination, contrôle, développement stratégique et propres activités.", en: "Steering, coordination, oversight, strategic development and its own activities." }, location: { fr: "Albanie / vocation internationale", en: "Albania / international vocation" } },
  "uab-gk-esttrade": { domain: { fr: "Commerce international, sourcing et développement Europe–Afrique", en: "International trade, sourcing and Europe–Africa development" }, role: { fr: "Développement des opérations commerciales et des relations Europe–Afrique.", en: "Development of trade operations and Europe–Africa relationships." }, legal: { fr: { title: "Informations légales", entries: [{ label: "Forme juridique", value: "UAB (société à responsabilité limitée)" }, { label: "Code société", value: "306154150" }, { label: "Siège social", value: "Vilnius, Lithuania" }, { label: "Immatriculée", value: "3 octobre 2022" }] }, en: { title: "Legal Information", entries: [{ label: "Legal form", value: "UAB (Private Limited Liability Company)" }, { label: "Company code", value: "306154150" }, { label: "Registered office", value: "Vilnius, Lithuania" }, { label: "Registered", value: "3 October 2022" }] } } },
  "gk-danube-trading": { domain: { fr: "Commerce et développement international", en: "Trade and international development" }, role: { fr: "Développement international en Serbie et dans la région.", en: "International development in Serbia and the region." } },
};
