import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { SectionTitle } from "@/components/ui/SectionTitle";
import { InstitutionalDiagram } from "@/components/ui/InstitutionalDiagram";

export function ArchitecturePage({ locale }) {
  const fr = locale === "fr";
  return <><Header locale={locale} /><main><section className="bg-[#061b46] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f5a24e]">GK GROUP</p><h1 className="mt-4 text-4xl font-bold sm:text-5xl">{fr ? "Notre architecture" : "Our architecture"}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-200">{fr ? "Une structure institutionnelle claire, conçue pour coordonner des expertises distinctes tout en soutenant le développement international." : "A clear institutional structure designed to coordinate distinct expertise while supporting international development."}</p></div></section><section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow={fr ? "Structure institutionnelle" : "Institutional structure"} title={fr ? "Un groupe, des structures aux rôles distincts" : "One group, structures with distinct roles"} /><InstitutionalDiagram locale={locale} /><p className="mt-8 max-w-4xl text-base leading-8 text-slate-600">{fr ? "GK GROUP représente l’architecture institutionnelle globale. GK GLOBAL GROUP SARLU est la société de référence juridique au Togo ; GKGT et GKGM en sont les branches opérationnelles. GK NEXUS, UAB GK-EstTrade et GK Danube Trading DOO sont des sociétés distinctes, coordonnées dans une logique de complémentarité et de développement international." : "GK GROUP represents the global institutional architecture. GK GLOBAL GROUP SARLU is the reference legal company in Togo, with GKGT and GKGM as its operational branches. GK NEXUS, UAB GK-EstTrade and GK Danube Trading DOO are distinct companies, coordinated through complementarity and international development."}</p></div></section><section className="bg-[#f5f7fa] px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow={fr ? "Comment elle fonctionne" : "How it works"} title={fr ? "Gouvernance, autonomie et coordination" : "Governance, autonomy and coordination"} /><div className="grid gap-4 md:grid-cols-3">{(fr ? [["Gouvernance", "Une référence institutionnelle claire pour les activités au Togo."], ["Autonomie opérationnelle", "Chaque société distincte conserve son rôle et son périmètre propres."], ["Développement international", "Les structures se complètent pour connecter des opportunités entre marchés."]] : [["Governance", "A clear institutional reference for activities in Togo."], ["Operational autonomy", "Each distinct company retains its own role and scope."], ["International development", "The structures complement one another to connect opportunities between markets."]]).map(([title, text]) => <article key={title} className="bg-white p-6"><h3 className="font-bold text-[#061b46]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section></main><Footer locale={locale} /></>;
}
