import Image from "next/image";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { CTA } from "@/components/ui/CTA";
import { SectionTitle } from "@/components/ui/SectionTitle";
import { ContactForm } from "@/components/pages/ContactForm";
import { CONTACT, CONTACT_CONTENT, ENTITY_LOGOS } from "@/content/site";
import { withLocale } from "@/lib/locale";

export function ContactPage({ locale, partnership }) {
  const copy = CONTACT_CONTENT[locale];
  const whatsappHref = `https://wa.me/22890559888?text=${encodeURIComponent(copy.details.whatsappMessage)}`;
  const actionClass = "inline-flex min-h-11 items-center justify-center border border-[#061b46] px-5 py-3 text-sm font-bold text-[#061b46] transition hover:bg-[#061b46] hover:text-white";
  return <><Header locale={locale} /><main>
    <section className="bg-[#061b46] text-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#f5a24e]">GK GROUP</p><div className="mt-5 h-px w-12 bg-[#e87512]" /><h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-6xl">{copy.hero.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">{copy.hero.description}</p><p className="mt-8 text-sm font-bold tracking-wide text-[#f5a24e]">{copy.hero.signature}</p></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.85fr_1.15fr]"><aside className="border-l-4 border-[#e87512] bg-[#f5f7fa] p-7 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e87512]">{copy.details.eyebrow}</p><h2 className="mt-4 text-3xl font-bold text-[#061b46]">{copy.details.title}</h2><address className="mt-6 not-italic leading-7 text-slate-600"><span className="block">Lomé, Togo</span><span className="block">Adidogomé-Soviépé</span><span className="mt-4 block text-xs font-bold uppercase tracking-wider text-slate-500">{copy.details.generalEmail}</span><a className="block font-bold text-[#061b46] hover:text-[#e87512]" href={CONTACT.generalEmailHref}>{CONTACT.generalEmail}</a><span className="mt-3 block text-xs font-bold uppercase tracking-wider text-slate-500">{copy.details.institutionalEmail}</span><a className="block font-bold text-[#061b46] hover:text-[#e87512]" href={CONTACT.emailHref}>{CONTACT.email}</a><a className="mt-3 block font-bold text-[#061b46] hover:text-[#e87512]" href={CONTACT.phoneHref}>{CONTACT.phone}</a><a className="block font-bold text-[#061b46] hover:text-[#e87512]" href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp: {CONTACT.whatsapp}</a></address><div className="mt-8 flex flex-wrap gap-3"><a className={actionClass} href={CONTACT.emailHref}>{copy.details.institutionalEmail}</a><a className={actionClass} href={CONTACT.phoneHref}>{copy.details.call}</a><a className={actionClass} href={whatsappHref} target="_blank" rel="noreferrer">{copy.details.whatsapp}</a></div></aside><div><SectionTitle eyebrow={copy.form.eyebrow} title={copy.form.title} /><ContactForm copy={copy} partnership={partnership} locale={locale} /></div></div></section>
    <section className="bg-[#f5f7fa] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow={copy.routing.eyebrow} title={copy.routing.title} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{copy.routing.items.map((item) => { const logo = ENTITY_LOGOS[item.id]; return <article key={item.id} className="border border-slate-200 bg-white p-6">{logo && <div className="mb-6 flex h-40 items-center justify-center border border-slate-200 bg-white p-4 sm:h-44 sm:p-5"><Image src={logo.src} alt={logo.alt} width={1536} height={1024} className="h-full w-full max-w-[20rem] object-contain" sizes="(max-width: 640px) 100vw, 360px" /></div>}<h3 className="text-lg font-bold text-[#061b46]">{item.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{item.text}</p></article>; })}</div></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl border-l-4 border-[#e87512] bg-[#f5f7fa] p-8 sm:flex sm:items-center sm:justify-between sm:gap-8 sm:p-12"><div><h2 className="max-w-xl text-3xl font-bold tracking-tight text-[#061b46] sm:text-4xl">{copy.partnership.title}</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">{copy.partnership.description}</p></div><div className="mt-8 sm:mt-0"><CTA href={`${withLocale("/contact", locale)}&area=partnership#contact-form`}>{copy.partnership.cta}</CTA></div></div></section>
  </main><Footer locale={locale} /></>;
}
