import Image from "next/image";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { CTA } from "@/components/ui/CTA";
import { SectionTitle } from "@/components/ui/SectionTitle";
import { NEXUS_CONTENT } from "@/content/site";
import { withLocale } from "@/lib/locale";

function FunctionalDiagram() {
  return <div className="mt-10 border border-slate-200 bg-[#f5f7fa] p-5 text-center sm:p-8"><div className="mx-auto w-fit bg-[#061b46] px-6 py-4 text-sm font-bold text-white">GK GROUP</div><div className="mx-auto h-7 w-px bg-[#e87512]" /><div className="mx-auto w-fit border-2 border-[#e87512] bg-white px-6 py-4 text-sm font-bold text-[#061b46]">GK NEXUS<br /><span className="font-normal text-slate-600">Corporate Coordination</span></div><div className="mx-auto h-7 w-px bg-[#e87512]" /><div className="grid gap-4 md:grid-cols-3"><div className="bg-white p-4 text-sm font-bold text-[#061b46]">GK GLOBAL GROUP SARLU<div className="mt-4 grid gap-2 border-t border-slate-200 pt-4 sm:grid-cols-2"><span>GKGT</span><span>GKGM</span></div></div><div className="bg-white p-4 text-sm font-bold text-[#061b46]">UAB GK EstTrade</div><div className="bg-white p-4 text-sm font-bold text-[#061b46]">GK Danube Trading DOO</div></div></div>;
}

export function NexusPage({ locale }) {
  const copy = NEXUS_CONTENT[locale];
  return <><Header locale={locale} /><main>
    <section className="bg-[#061b46] text-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#f5a24e]">{copy.hero.eyebrow}</p><div className="mt-5 h-px w-12 bg-[#e87512]" /><h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-6xl">{copy.hero.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">{copy.hero.description}</p><p className="mt-8 border-l-2 border-[#e87512] pl-4 text-sm font-bold text-[#f5a24e]">{copy.hero.location}</p><div className="mt-8 flex h-28 w-full max-w-xs items-center border border-white/20 bg-white p-4 shadow-lg shadow-black/20"><Image src="/brand/entities/gk-nexus.png" alt="Logo GK NEXUS" width={1536} height={1024} className="h-full w-full object-contain" sizes="320px" /></div></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow={copy.vocation.eyebrow} title={copy.vocation.title} /><div className="grid gap-5 lg:grid-cols-2"><article className="border-t-4 border-[#e87512] bg-[#f5f7fa] p-7 sm:p-8"><h2 className="text-2xl font-bold text-[#061b46]">{copy.vocation.corporate.title}</h2><ul className="mt-6 grid gap-3 text-sm leading-6 text-slate-600">{copy.vocation.corporate.items.map((item) => <li key={item} className="border-l-2 border-[#e87512] pl-3">{item}</li>)}</ul></article><article className="bg-[#061b46] p-7 text-white sm:p-8"><h2 className="text-2xl font-bold">{copy.vocation.operations.title}</h2><p className="mt-5 leading-7 text-slate-200">{copy.vocation.operations.description}</p><ul className="mt-6 grid gap-3 text-sm font-bold">{copy.vocation.operations.items.map((item) => <li key={item} className="border-t border-white/15 pt-3">{item}</li>)}</ul></article></div></div></section>
    <section className="bg-[#f5f7fa] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><SectionTitle eyebrow={copy.role.eyebrow} title={copy.role.title} /><p className="max-w-3xl text-lg leading-8 text-slate-600">{copy.role.description}</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{copy.role.items.map((item) => <li key={item} className="bg-white p-4 text-sm font-bold leading-6 text-[#061b46]">{item}</li>)}</ul></div><div className="self-center"><CTA href={withLocale("/architecture", locale)}>{copy.role.cta}</CTA></div></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="border-l-4 border-[#e87512] bg-[#f5f7fa] p-7 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e87512]">{copy.albania.eyebrow}</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-[#061b46]">{copy.albania.title}</h2><p className="mt-5 leading-7 text-slate-600">{copy.albania.description}</p></div><ul className="grid gap-3 sm:grid-cols-2">{copy.albania.items.map((item) => <li key={item} className="border border-slate-200 p-5 text-sm leading-6 text-slate-600">{item}</li>)}</ul></div></section>
    <section className="bg-[#f5f7fa] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow={copy.diagram.eyebrow} title={copy.diagram.title} /><FunctionalDiagram /><p className="mt-6 max-w-3xl text-sm leading-6 text-slate-600">{copy.diagram.note}</p></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow={copy.value.eyebrow} title={copy.value.title} /><ol className="grid gap-4 md:grid-cols-5">{copy.value.steps.map((step, index) => <li key={step} className="bg-[#061b46] p-5 text-center text-sm font-bold leading-6 text-white"><span className="mb-3 block text-[#f5a24e]">0{index + 1}</span>{step}</li>)}</ol></div></section>
    <section className="bg-[#f5f7fa] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow={copy.interactions.eyebrow} title={copy.interactions.title} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{copy.interactions.items.map((item) => <article key={item.name} className="border border-slate-200 bg-white p-6"><h3 className="text-lg font-bold text-[#061b46]">{item.name}</h3><p className="mt-4 text-sm leading-6 text-slate-600">{item.text}</p></article>)}</div></div></section>
    <section className="bg-[#061b46] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f5a24e]">{copy.vision.eyebrow}</p><h2 className="mt-4 max-w-3xl text-3xl font-bold tracking-tight sm:text-4xl">{copy.vision.title}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">{copy.vision.description}</p></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl border-l-4 border-[#e87512] bg-[#f5f7fa] p-8 sm:flex sm:items-center sm:justify-between sm:gap-8 sm:p-12"><h2 className="max-w-xl text-3xl font-bold tracking-tight text-[#061b46] sm:text-4xl">{copy.final.title}</h2><div className="mt-8 flex flex-wrap gap-4 sm:mt-0"><CTA href={withLocale("/entities", locale)}>{copy.final.entities}</CTA><CTA href={withLocale("/contact", locale)}>{copy.final.contact}</CTA></div></div></section>
  </main><Footer locale={locale} /></>;
}
